steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    # dir: 'disastermanagement-repo'
    args: ['build', '-t', 'asia-docker.pkg.dev/$PROJECT_ID/my-docker-images-repo/disastermanagement:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-docker.pkg.dev/$PROJECT_ID/my-docker-images-repo/disastermanagement:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'beta'
      - 'run'
      - 'deploy'
      - 'disastermanagementcloudrun'
      - '--image'
      - 'asia-docker.pkg.dev/$PROJECT_ID/my-docker-images-repo/disastermanagement:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '1'
      - '--allow-unauthenticated'

images:
  - 'us-docker.pkg.dev/$PROJECT_ID/gcr/disastermanagement'

options:
  logging: CLOUD_LOGGING_ONLY

#logsBucket: 'gs://log-bucket-1/'
