# steps:
#   # Build the container image
#   - name: 'gcr.io/cloud-builders/docker'
#     # dir: 'disastermanagement-repo'
#     args: ['build', '-t', 'asia-docker.pkg.dev/$PROJECT_ID/disastermanagemant/main:$COMMIT_SHA', '.']

#   # Push the container image to Container Registry
#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['push', 'asia-docker.pkg.dev/$PROJECT_ID/disastermangement/main:$COMMIT_SHA']
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', "$AR_IMAGE", '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', "$AR_IMAGE"]


  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'beta'
      - 'run'
      - 'deploy'
      - 'disastermanagementcloudrun'
      - '--image'
      - 'asia-docker.pkg.dev/$PROJECT_ID/disastermangement/main:$COMMIT_SHA'
      - '--region'
      - 'us-east1'
      - '--platform'
      - 'managed'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '1'
      - '--allow-unauthenticated'
images:
  - "$AR_IMAGE"
# images:
#   - 'us-docker.pkg.dev/$PROJECT_ID/gcr/disastermanagement'

options:
  logging: CLOUD_LOGGING_ONLY

#logsBucket: 'gs://log-bucket-1/'
